namespace TS3CallsignHelper.Api;
public enum PlaneState {
  IS_GND = 0x01,
  IS_TWR = 0x02,
  IS_DEP = 0x04,
  IS_INCOMING = 0x10,
  IS_GND_INIT = 0x10,
  IS_TWR_INIT = 0x20,
  IS_DEP_INIT = 0x40,
  IS_RADIO_AWAY = 0x80,

  UNKNOWN = 0,

  OUT_STARTUP_REQUEST =          0x100 | IS_GND | IS_GND_INIT,
  OUT_PUSHBACK_REQUEST =         0x200 | IS_GND | IS_GND_INIT,
  OUT_STARTUP_PROGRESS =         0x300 | IS_GND,
  OUT_PUSHBACK_PROGRESS =        0x400 | IS_GND,
  OUT_TAXI_REQUEST =             0x500 | IS_GND,
  OUT_TAXI_PROGRESS =            0x600 | IS_GND,
  OUT_RWY_WAITING =              0x700 | IS_TWR | IS_TWR_INIT,
  OUT_RWY_LINE_UP =              0x800 | IS_TWR,
  OUT_RWY_LINE_UP_BEHIND =       0x900 | IS_TWR,
  OUT_RWY_TAKEOFF =              0xa00 | IS_TWR,
  OUT_DEPARTURE =                0xb00 | IS_DEP | IS_DEP_INIT,

  IN_RWY_APPROACH =              0xc00 | IS_INCOMING | IS_TWR | IS_TWR_INIT,
  IN_RWY_CLR_LAND =              0xd00 | IS_INCOMING | IS_TWR,
  IN_RWY_CLR_LAHS =              0xe00 | IS_INCOMING | IS_TWR,
  IN_RWY_CLR_LAPP =              0xf00 | IS_INCOMING | IS_TWR,
  IN_RWY_CLR_TAGO =             0x1000 | IS_INCOMING | IS_TWR,
  IN_RWY_CLR_SAGO =             0x1100 | IS_INCOMING | IS_TWR,
  IN_RWY_GO_AROUND =            0x1200 | IS_INCOMING | IS_TWR,
  IN_RWY_WAITING =              0x1300 | IS_INCOMING | IS_TWR,
  IN_TAXI_REQUEST =             0x1400 | IS_INCOMING | IS_GND | IS_GND_INIT,
  IN_TAXI_PROGRESS =            0x1500 | IS_INCOMING | IS_GND,
  IN_AT_TERMINAL =              0x1600 | IS_INCOMING | IS_GND,

  OUT_RAD_LEAVE =                  0x0 | IS_RADIO_AWAY | IS_GND | IS_TWR | IS_DEP,
  IN_RAD_LEAVE =                   0x0 | IS_RADIO_AWAY | IS_INCOMING | IS_GND | IS_TWR | IS_DEP,
}
