//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS3CallsignHelper.Modules.PlaneState.Translation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlaneStateModule {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlaneStateModule() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TS3CallsignHelper.Modules.PlaneState.Translation.PlaneStateModule", typeof(PlaneStateModule).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string Direction_In {
            get {
                return ResourceManager.GetString("Direction_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string Direction_Out {
            get {
                return ResourceManager.GetString("Direction_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_AT_TERMINAL {
            get {
                return ResourceManager.GetString("State_IN_AT_TERMINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RAD_LEAVE {
            get {
                return ResourceManager.GetString("State_IN_RAD_LEAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RWY_APPROACH {
            get {
                return ResourceManager.GetString("State_IN_RWY_APPROACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RWY_CLR_LAHS {
            get {
                return ResourceManager.GetString("State_IN_RWY_CLR_LAHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RWY_CLR_LAND {
            get {
                return ResourceManager.GetString("State_IN_RWY_CLR_LAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RWY_CLR_LAPP {
            get {
                return ResourceManager.GetString("State_IN_RWY_CLR_LAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RWY_CLR_SAGO {
            get {
                return ResourceManager.GetString("State_IN_RWY_CLR_SAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RWY_CLR_TAGO {
            get {
                return ResourceManager.GetString("State_IN_RWY_CLR_TAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RWY_GO_AROUND {
            get {
                return ResourceManager.GetString("State_IN_RWY_GO_AROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_RWY_WAITING {
            get {
                return ResourceManager.GetString("State_IN_RWY_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_TAXI_PROGRESS {
            get {
                return ResourceManager.GetString("State_IN_TAXI_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_IN_TAXI_REQUEST {
            get {
                return ResourceManager.GetString("State_IN_TAXI_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_DEPARTURE {
            get {
                return ResourceManager.GetString("State_OUT_DEPARTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_PUSHBACK_PROGRESS {
            get {
                return ResourceManager.GetString("State_OUT_PUSHBACK_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_PUSHBACK_REQUEST {
            get {
                return ResourceManager.GetString("State_OUT_PUSHBACK_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_RAD_LEAVE {
            get {
                return ResourceManager.GetString("State_OUT_RAD_LEAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_RWY_LINE_UP {
            get {
                return ResourceManager.GetString("State_OUT_RWY_LINE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_RWY_LINE_UP_BEHIND {
            get {
                return ResourceManager.GetString("State_OUT_RWY_LINE_UP_BEHIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_RWY_TAKEOFF {
            get {
                return ResourceManager.GetString("State_OUT_RWY_TAKEOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_RWY_WAITING {
            get {
                return ResourceManager.GetString("State_OUT_RWY_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_STARTUP_PROGRESS {
            get {
                return ResourceManager.GetString("State_OUT_STARTUP_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_STARTUP_REQUEST {
            get {
                return ResourceManager.GetString("State_OUT_STARTUP_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_TAXI_PROGRESS {
            get {
                return ResourceManager.GetString("State_OUT_TAXI_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string State_OUT_TAXI_REQUEST {
            get {
                return ResourceManager.GetString("State_OUT_TAXI_REQUEST", resourceCulture);
            }
        }
    }
}
